- name: Install Shorewall
  apt: pkg=shorewall update_cache=yes
- name: Configure Shorewall Interfaces 
  template: src="interfaces.j2" dest="/etc/shorewall/interfaces" owner=root group=root mode=0644
  notify:
   - restart shorewall
- name: Configure Shorewall Policy
  template: src="policy.j2" dest="/etc/shorewall/policy" owner=root group=root mode=0644
  notify:
   - restart shorewall
- name: Configure Shorewall Rules
  template: src="rules.j2" dest="/etc/shorewall/rules" owner=root group=root mode=0644
  notify:
   - restart shorewall
- name: Configure Shorewall 
  template: src="shorewall.j2" dest="/etc/shorewall/shorewall.conf" owner=root group=root mode=0644
  notify:
   - restart shorewall
- name: Configure Shorewall Zones
  template: src="zones.j2" dest="/etc/shorewall/zones" owner=root group=root mode=0644
  notify:
   - restart shorewall
- name: Enable Shorewall
  lineinfile: dest=/etc/default/shorewall regexp="^startup=0" line="startup=1"
  notify: 
   - restart shorewall
