- name: Install rsyslog Debian
  apt: pkg={{ item }} state=installed
  with_items:
   - rsyslog
- name: Copy Rsyslog Conf
  template: src="rsyslog.j2" dest="/etc/rsyslog.conf" owner=root group=root mode=0644
  notify:
   - restart rsyslog
